export default [
    {name: "scheme-aqua",value: "#00ffff",free: true},
    {name: "scheme-azure",value: "#f0ffff",free: true},
    {name: "scheme-beige",value: "#f5f5dc",free: true},
    {name: "scheme-black",value: "#000000",free: true},
    {name: "scheme-blue",value: "#0000ff",free: true},
    {name: "scheme-brown",value: "#a52a2a",free: true},
    {name: "scheme-cyan",value: "#00ffff",free: true},
    {name: "scheme-darkblue",value: "#00008b",free: true},
    {name: "scheme-darkcyan",value: "#008b8b",free: true},
    {name: "scheme-darkgreen",value: "#006400",free: true},
    {name: "scheme-darkkhaki",value: "#bdb76b",free: true},
    {name: "scheme-darkmagenta",value: "#8b008b",free: true},
    {name: "scheme-darkolivegreen",value: "#556b2f",free: true},
    {name: "scheme-darkorange",value: "#ff8c00",free: true},
    {name: "scheme-darkorchid",value: "#9932cc",free: true},
    {name: "scheme-darkred",value: "#8b0000",free: true},
    {name: "scheme-darksalmon",value: "#e9967a",free: true},
    {name: "scheme-darkviolet",value:"#9400d3",free: true},
    {name: "scheme-fuchsia",value: "#ff00ff",free: true},
    {name: "scheme-gold",value: "#ffd700",free: true},
    {name: "scheme-green",value: "#008000",free: true},
    {name: "scheme-indigo",value: "#4b0082",free: true},
    {name: "scheme-khaki",value: "#f0e68c",free: true},
    {name: "scheme-lime",value: "#00ff00",free: true},
    {name: "scheme-magenta",value: "#ff00ff",free: true},
    {name: "scheme-maroon",value: "#800000",free: true},
    {name: "scheme-navy",value: "#000080",free: true},
    {name: "scheme-olive",value: "#808000",free: true},
    {name: "scheme-orange",value: "#ffa500",free: true},
    {name: "scheme-pink",value: "#ffc0cb",free: true},
    {name: "scheme-purple",value: "#800080",free: true},
    {name: "scheme-violet", value: "#800080",free: true},
    {name: "scheme-red", value: "#ff0000",free: true},
    {name: "scheme-silver", value:  "#c0c0c0",free: true}
]